### ISSUE TITLE
js.forEach is not a function

### ISSUE THREAD

**Issue by xavruss** [protobi/js-xlsx#184]
Uncaught (in promise) TypeError: js.forEach is not a function
    at sheet_add_json (xlsx.js:21165:1)
    at Object.json_to_sheet (xlsx.js:21200:1)
    at js.js:1791:1
    at new Promise (<anonymous>)
    at Eventscolas.bal (js.js:1789:1)
    at Eventscolas.bak (js.js:1783:1)
    at onClick (top_titles.js:73:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)

**Comment by memory-tapes** [comment]
I think you need to provide more context about how you are including this library.
